{
 "title": "Pizza Dashboard",
 "time": { "from": "2026-03-04T21:30:14.703Z", "to": "2026-03-06T21:30:14.703Z" },
 "panels": [
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(requests_total{endpoint=\"[GET]\", source=\"jwt-pizza-service\"}[1m])) or vector(0)",
     "legendFormat": "get"
    },
    {
     "expr": "sum(rate(requests_total{endpoint=\"[POST]\", source=\"jwt-pizza-service\"}[1m])) or vector(0)",
     "legendFormat": "post"
    },
    {
     "expr": "sum(rate(requests_total{endpoint=\"[PUT]\", source=\"jwt-pizza-service\"}[1m])) or vector(0)",
     "legendFormat": "put"
    },
    {
     "expr": "sum(rate(requests_total{endpoint=\"[DELETE]\", source=\"jwt-pizza-service\"}[1m])) or vector(0)",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(rate(requests_total{source=\"jwt-pizza-service\"}[1m])) or vector(0)",
     "legendFormat": "total request"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(auth_total{status=\"200\", source=\"jwt-pizza-service\"}[1m])) or vector(0)",
     "legendFormat": "success"
    },
    {
     "expr": "sum(rate(auth_total{status!=\"200\", source=\"jwt-pizza-service\"}[1m])) or vector(0)",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(pizza_total{status=\"200\", source=\"jwt-pizza-service\"}[1m])) or vector(0)",
     "legendFormat": "purchase success"
    },
    {
     "expr": "sum(rate(pizza_total{status!=\"200\", source=\"jwt-pizza-service\"}[1m])) or vector(0)",
     "legendFormat": "purchase failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(pizza_price_total{source=\"jwt-pizza-service\"}[1m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(request_latency_milliseconds{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "request latency"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time(pizza_latency_milliseconds{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "pizza latency"
    }
   ]
  }
 ]
}